spring.datasource.url=jdbc:postgresql://taskflow-postgres:5432/taskflow
spring.datasource.username=taskflow
spring.datasource.password=taskflow_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
